package com.icloud.insurance.model;

// Generated 2015-3-13 17:25:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * InsuranceProduct generated by hbm2java
 */
public class InsuranceProduct implements java.io.Serializable {

	private Integer id;
	private String insuranceName;
	private String insuranceCompany;
	private String simpleDescription;
	private Integer safeguardTime;
	private Date crateTime;
	private Date lastUpdateTime;
	private Integer lastUpdateUserId;
	private String lastUpdateUserName;
	private Integer insuranceStatus;

	public InsuranceProduct() {
	}

	public InsuranceProduct(String insuranceName, String insuranceCompany,
			String simpleDescription, Integer safeguardTime, Date crateTime,
			Date lastUpdateTime, Integer lastUpdateUserId,
			String lastUpdateUserName, Integer insuranceStatus) {
		this.insuranceName = insuranceName;
		this.insuranceCompany = insuranceCompany;
		this.simpleDescription = simpleDescription;
		this.safeguardTime = safeguardTime;
		this.crateTime = crateTime;
		this.lastUpdateTime = lastUpdateTime;
		this.lastUpdateUserId = lastUpdateUserId;
		this.lastUpdateUserName = lastUpdateUserName;
		this.insuranceStatus = insuranceStatus;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getInsuranceName() {
		return this.insuranceName;
	}

	public void setInsuranceName(String insuranceName) {
		this.insuranceName = insuranceName;
	}

	public String getInsuranceCompany() {
		return this.insuranceCompany;
	}

	public void setInsuranceCompany(String insuranceCompany) {
		this.insuranceCompany = insuranceCompany;
	}

	public String getSimpleDescription() {
		return this.simpleDescription;
	}

	public void setSimpleDescription(String simpleDescription) {
		this.simpleDescription = simpleDescription;
	}

	public Integer getSafeguardTime() {
		return this.safeguardTime;
	}

	public void setSafeguardTime(Integer safeguardTime) {
		this.safeguardTime = safeguardTime;
	}

	public Date getCrateTime() {
		return this.crateTime;
	}

	public void setCrateTime(Date crateTime) {
		this.crateTime = crateTime;
	}

	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	public Integer getLastUpdateUserId() {
		return this.lastUpdateUserId;
	}

	public void setLastUpdateUserId(Integer lastUpdateUserId) {
		this.lastUpdateUserId = lastUpdateUserId;
	}

	public String getLastUpdateUserName() {
		return this.lastUpdateUserName;
	}

	public void setLastUpdateUserName(String lastUpdateUserName) {
		this.lastUpdateUserName = lastUpdateUserName;
	}

	public Integer getInsuranceStatus() {
		return this.insuranceStatus;
	}

	public void setInsuranceStatus(Integer insuranceStatus) {
		this.insuranceStatus = insuranceStatus;
	}

}
