// default package
// Generated Mar 20, 2015 10:36:46 PM by Hibernate Tools 3.4.0.CR1

/**
 * InsuranceAttribute generated by hbm2java
 */
public class InsuranceAttribute implements java.io.Serializable {

	private Integer id;
	private Integer fatherId;
	private String attributeName;
	private String fatherName;
	private Integer status;
	private Integer level;
	private String uuid;

	public InsuranceAttribute() {
	}

	public InsuranceAttribute(Integer fatherId, String attributeName,
			String fatherName, Integer status, Integer level, String uuid) {
		this.fatherId = fatherId;
		this.attributeName = attributeName;
		this.fatherName = fatherName;
		this.status = status;
		this.level = level;
		this.uuid = uuid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getFatherId() {
		return this.fatherId;
	}

	public void setFatherId(Integer fatherId) {
		this.fatherId = fatherId;
	}

	public String getAttributeName() {
		return this.attributeName;
	}

	public void setAttributeName(String attributeName) {
		this.attributeName = attributeName;
	}

	public String getFatherName() {
		return this.fatherName;
	}

	public void setFatherName(String fatherName) {
		this.fatherName = fatherName;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

}
