package com.icloud.stock.model;

// Generated Nov 22, 2014 10:22:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * JuhuasuanDetail generated by hbm2java
 */
public class JuhuasuanDetail implements java.io.Serializable {

	private Integer id;
	private String perfer;
	private String perferHost;
	private String perferIp;
	private String urlId;
	private Date createTime;
	private String otherParam;
	private Integer userId;
	private Integer valid;

	public JuhuasuanDetail() {
	}

	public JuhuasuanDetail(String perfer, String perferHost, String perferIp,
			String urlId, Date createTime, String otherParam, Integer userId,
			Integer valid) {
		this.perfer = perfer;
		this.perferHost = perferHost;
		this.perferIp = perferIp;
		this.urlId = urlId;
		this.createTime = createTime;
		this.otherParam = otherParam;
		this.userId = userId;
		this.valid = valid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPerfer() {
		return this.perfer;
	}

	public void setPerfer(String perfer) {
		this.perfer = perfer;
	}

	public String getPerferHost() {
		return this.perferHost;
	}

	public void setPerferHost(String perferHost) {
		this.perferHost = perferHost;
	}

	public String getPerferIp() {
		return this.perferIp;
	}

	public void setPerferIp(String perferIp) {
		this.perferIp = perferIp;
	}

	public String getUrlId() {
		return this.urlId;
	}

	public void setUrlId(String urlId) {
		this.urlId = urlId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getOtherParam() {
		return this.otherParam;
	}

	public void setOtherParam(String otherParam) {
		this.otherParam = otherParam;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getValid() {
		return this.valid;
	}

	public void setValid(Integer valid) {
		this.valid = valid;
	}

}
