package com.icloud.stock.model;

// Generated Jan 29, 2015 9:21:11 PM by Hibernate Tools 3.4.0.CR1

/**
 * MarketingChannel generated by hbm2java
 */
public class MarketingChannel implements java.io.Serializable {

	private Integer id;
	private String channelName;

	public MarketingChannel() {
	}

	public MarketingChannel(String channelName) {
		this.channelName = channelName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getChannelName() {
		return this.channelName;
	}

	public void setChannelName(String channelName) {
		this.channelName = channelName;
	}

}
