package com.icloud.stock.model;

// Generated Jan 29, 2015 9:21:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Paper generated by hbm2java
 */
public class Paper implements java.io.Serializable {

	private Integer id;
	private String title;
	private String content;
	private String originTitle;
	private String originUrl;
	private String originWebsite;
	private String channel;
	private Integer count;
	private Date createTime;
	private Date updateTime;

	public Paper() {
	}

	public Paper(String title, String content, String originTitle,
			String originUrl, String originWebsite, String channel,
			Integer count, Date createTime, Date updateTime) {
		this.title = title;
		this.content = content;
		this.originTitle = originTitle;
		this.originUrl = originUrl;
		this.originWebsite = originWebsite;
		this.channel = channel;
		this.count = count;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getOriginTitle() {
		return this.originTitle;
	}

	public void setOriginTitle(String originTitle) {
		this.originTitle = originTitle;
	}

	public String getOriginUrl() {
		return this.originUrl;
	}

	public void setOriginUrl(String originUrl) {
		this.originUrl = originUrl;
	}

	public String getOriginWebsite() {
		return this.originWebsite;
	}

	public void setOriginWebsite(String originWebsite) {
		this.originWebsite = originWebsite;
	}

	public String getChannel() {
		return this.channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
