package com.icloud.stock.model;

// Generated Jan 29, 2015 9:21:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UserFriend generated by hbm2java
 */
public class UserFriend implements java.io.Serializable {

	private Integer id;
	private Integer userId;
	private Integer friendId;
	private Integer status;
	private Date createTime;
	private Date updateTime;
	private String description;
	private String userName;
	private String userRelation;

	public UserFriend() {
	}

	public UserFriend(Integer userId, Integer friendId, Integer status,
			Date createTime, Date updateTime, String description,
			String userName, String userRelation) {
		this.userId = userId;
		this.friendId = friendId;
		this.status = status;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.description = description;
		this.userName = userName;
		this.userRelation = userRelation;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getFriendId() {
		return this.friendId;
	}

	public void setFriendId(Integer friendId) {
		this.friendId = friendId;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserRelation() {
		return this.userRelation;
	}

	public void setUserRelation(String userRelation) {
		this.userRelation = userRelation;
	}

}
