package com.icloud.stock.model;

// Generated Oct 22, 2014 11:19:00 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UserUrlAccessCount generated by hbm2java
 */
public class UserUrlAccessCount implements java.io.Serializable {

	private Integer id;
	private Integer userId;
	private Integer count;
	private Integer allCount;
	private Date createTime;

	public UserUrlAccessCount() {
	}

	public UserUrlAccessCount(Integer userId, Integer count, Integer allCount,
			Date createTime) {
		this.userId = userId;
		this.count = count;
		this.allCount = allCount;
		this.createTime = createTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public Integer getAllCount() {
		return this.allCount;
	}

	public void setAllCount(Integer allCount) {
		this.allCount = allCount;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
