package com.icloud.insurance.model;

// Generated 2015-3-12 15:18:54 by Hibernate Tools 3.4.0.CR1

/**
 * InsuranceAttri generated by hbm2java
 */
public class InsuranceAttri implements java.io.Serializable {

	private Integer id;
	private String category;
	private String attributeName;

	public InsuranceAttri() {
	}

	public InsuranceAttri(String category, String attributeName) {
		this.category = category;
		this.attributeName = attributeName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getAttributeName() {
		return this.attributeName;
	}

	public void setAttributeName(String attributeName) {
		this.attributeName = attributeName;
	}

}
