package com.icloud.insurance.model;

// Generated 2015-3-12 15:18:54 by Hibernate Tools 3.4.0.CR1

/**
 * InsuranceNumber generated by hbm2java
 */
public class InsuranceNumber implements java.io.Serializable {

	private Integer id;
	private Integer order;
	private Integer value;
	private String description;
	private Integer insuranceId;
	private Integer insuranceAttriId;
	private Integer insuranceCategroryId;

	public InsuranceNumber() {
	}

	public InsuranceNumber(Integer order, Integer value, String description,
			Integer insuranceId, Integer insuranceAttriId,
			Integer insuranceCategroryId) {
		this.order = order;
		this.value = value;
		this.description = description;
		this.insuranceId = insuranceId;
		this.insuranceAttriId = insuranceAttriId;
		this.insuranceCategroryId = insuranceCategroryId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getOrder() {
		return this.order;
	}

	public void setOrder(Integer order) {
		this.order = order;
	}

	public Integer getValue() {
		return this.value;
	}

	public void setValue(Integer value) {
		this.value = value;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getInsuranceId() {
		return this.insuranceId;
	}

	public void setInsuranceId(Integer insuranceId) {
		this.insuranceId = insuranceId;
	}

	public Integer getInsuranceAttriId() {
		return this.insuranceAttriId;
	}

	public void setInsuranceAttriId(Integer insuranceAttriId) {
		this.insuranceAttriId = insuranceAttriId;
	}

	public Integer getInsuranceCategroryId() {
		return this.insuranceCategroryId;
	}

	public void setInsuranceCategroryId(Integer insuranceCategroryId) {
		this.insuranceCategroryId = insuranceCategroryId;
	}

}
