package com.icloud.insurance.model;

// Generated 2015-3-12 15:18:54 by Hibernate Tools 3.4.0.CR1

/**
 * InsuranceProduct generated by hbm2java
 */
public class InsuranceProduct implements java.io.Serializable {

	private Integer id;
	private String insuranceName;
	private String insuranceCompany;
	private String simpleDescription;
	private Integer safeguardTime;

	public InsuranceProduct() {
	}

	public InsuranceProduct(String insuranceName, String insuranceCompany,
			String simpleDescription, Integer safeguardTime) {
		this.insuranceName = insuranceName;
		this.insuranceCompany = insuranceCompany;
		this.simpleDescription = simpleDescription;
		this.safeguardTime = safeguardTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getInsuranceName() {
		return this.insuranceName;
	}

	public void setInsuranceName(String insuranceName) {
		this.insuranceName = insuranceName;
	}

	public String getInsuranceCompany() {
		return this.insuranceCompany;
	}

	public void setInsuranceCompany(String insuranceCompany) {
		this.insuranceCompany = insuranceCompany;
	}

	public String getSimpleDescription() {
		return this.simpleDescription;
	}

	public void setSimpleDescription(String simpleDescription) {
		this.simpleDescription = simpleDescription;
	}

	public Integer getSafeguardTime() {
		return this.safeguardTime;
	}

	public void setSafeguardTime(Integer safeguardTime) {
		this.safeguardTime = safeguardTime;
	}

}
