package com.icloud.insurance.model;

// default package
// Generated Mar 20, 2015 10:36:46 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * MediaFile generated by hbm2java
 */
public class MediaFile implements java.io.Serializable {

	private Integer id;
	private String fileName;
	private String fileHashId;
	private Date createTime;
	private Date lastUpdateTime;
	private String fileType;
	private Integer fileSize;
	private byte[] fileBytes;

	public MediaFile() {
	}

	public MediaFile(String fileName, String fileHashId, Date createTime,
			Date lastUpdateTime, String fileType, Integer fileSize,
			byte[] fileBytes) {
		this.fileName = fileName;
		this.fileHashId = fileHashId;
		this.createTime = createTime;
		this.lastUpdateTime = lastUpdateTime;
		this.fileType = fileType;
		this.fileSize = fileSize;
		this.fileBytes = fileBytes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getFileHashId() {
		return this.fileHashId;
	}

	public void setFileHashId(String fileHashId) {
		this.fileHashId = fileHashId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	public String getFileType() {
		return this.fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	public Integer getFileSize() {
		return this.fileSize;
	}

	public void setFileSize(Integer fileSize) {
		this.fileSize = fileSize;
	}

	public byte[] getFileBytes() {
		return this.fileBytes;
	}

	public void setFileBytes(byte[] fileBytes) {
		this.fileBytes = fileBytes;
	}

}
