package com.icloud.stock.model;
// default package
// Generated Oct 4, 2014 1:08:15 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * JuhuasuanUrl generated by hbm2java
 */
public class JuhuasuanUrl implements java.io.Serializable {

	private Integer id;
	private String name;
	private String taobaoUrl;
	private String icloudUrl;
	private int userId;
	private Date createTime;
	private Date updateTime;
	private String desText;

	public JuhuasuanUrl() {
	}

	public JuhuasuanUrl(String name, String taobaoUrl, String icloudUrl,
			int userId, Date createTime, Date updateTime) {
		this.name = name;
		this.taobaoUrl = taobaoUrl;
		this.icloudUrl = icloudUrl;
		this.userId = userId;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public JuhuasuanUrl(String name, String taobaoUrl, String icloudUrl,
			int userId, Date createTime, Date updateTime, String desText) {
		this.name = name;
		this.taobaoUrl = taobaoUrl;
		this.icloudUrl = icloudUrl;
		this.userId = userId;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.desText = desText;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTaobaoUrl() {
		return this.taobaoUrl;
	}

	public void setTaobaoUrl(String taobaoUrl) {
		this.taobaoUrl = taobaoUrl;
	}

	public String getIcloudUrl() {
		return this.icloudUrl;
	}

	public void setIcloudUrl(String icloudUrl) {
		this.icloudUrl = icloudUrl;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getDesText() {
		return this.desText;
	}

	public void setDesText(String desText) {
		this.desText = desText;
	}

}
