package com.icloud.stock.model;

// Generated Oct 7, 2014 5:54:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * JuhuasuanUrlVO generated by hbm2java
 */
public class JuhuasuanUrl implements java.io.Serializable {

	private Integer id;
	private String name;
	private String taobaoUrl;
	private String icloudUrl;
	private int userId;
	private Date createTime;
	private Date updateTime;
	private String desText;
	private String status;
	private String type;
	private String solidify;
	private String originUrl;

	public JuhuasuanUrl() {
	}

	public JuhuasuanUrl(String name, String taobaoUrl, int userId,
			Date createTime, Date updateTime) {
		this.name = name;
		this.taobaoUrl = taobaoUrl;
		this.userId = userId;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public JuhuasuanUrl(String name, String taobaoUrl, String icloudUrl,
			int userId, Date createTime, Date updateTime, String desText,
			String status, String type, String solidify, String originUrl) {
		this.name = name;
		this.taobaoUrl = taobaoUrl;
		this.icloudUrl = icloudUrl;
		this.userId = userId;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.desText = desText;
		this.status = status;
		this.type = type;
		this.solidify = solidify;
		this.originUrl = originUrl;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTaobaoUrl() {
		return this.taobaoUrl;
	}

	public void setTaobaoUrl(String taobaoUrl) {
		this.taobaoUrl = taobaoUrl;
	}

	public String getIcloudUrl() {
		return this.icloudUrl;
	}

	public void setIcloudUrl(String icloudUrl) {
		this.icloudUrl = icloudUrl;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getDesText() {
		return this.desText;
	}

	public void setDesText(String desText) {
		this.desText = desText;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getSolidify() {
		return this.solidify;
	}

	public void setSolidify(String solidify) {
		this.solidify = solidify;
	}

	public String getOriginUrl() {
		return this.originUrl;
	}

	public void setOriginUrl(String originUrl) {
		this.originUrl = originUrl;
	}

	@Override
	public String toString() {
		return "JuhuasuanUrl [id=" + id + ", name=" + name + ", taobaoUrl="
				+ taobaoUrl + ", icloudUrl=" + icloudUrl + ", userId=" + userId
				+ ", createTime=" + createTime + ", updateTime=" + updateTime
				+ ", desText=" + desText + ", status=" + status + ", type="
				+ type + ", solidify=" + solidify + ", originUrl=" + originUrl
				+ "]";
	}

}
