package com.icloud.stock.model;

// Generated Nov 25, 2014 4:56:53 PM by Hibernate Tools 3.4.0.CR1

/**
 * MarketingChannel generated by hbm2java
 */
public class MarketingChannel implements java.io.Serializable {

	private int id;
	private String channelName;

	public MarketingChannel() {
	}

	public MarketingChannel(int id) {
		this.id = id;
	}

	public MarketingChannel(int id, String channelName) {
		this.id = id;
		this.channelName = channelName;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getChannelName() {
		return this.channelName;
	}

	public void setChannelName(String channelName) {
		this.channelName = channelName;
	}

}
