package com.icloud.stock.model;

// Generated Nov 22, 2014 10:22:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TaobaoConstant generated by hbm2java
 */
public class TaobaoConstant implements java.io.Serializable {

	private Integer id;
	private String name;
	private String value;
	private Date updateTime;
	private Integer userId;
	private String userName;

	public TaobaoConstant() {
	}

	public TaobaoConstant(String name, String value, Date updateTime,
			Integer userId, String userName) {
		this.name = name;
		this.value = value;
		this.updateTime = updateTime;
		this.userId = userId;
		this.userName = userName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

}
